# Pygame constants.
FPS = 60
CAPTION = "Dungeon Breakout"

# Screen constants.
DEFAULT_ZOOM_SCALE = 2
MIN_ZOOM_SCALE = 1
MAX_ZOOM_SCALE = 2

# Animation constants.
NORMAL_ANIMATION_SPEED = 0.15
SWINGING_ANIMATION_SPEED = 0.25
SCALE_SPEED = 0.1
FLASH_STEP_FRAME = FPS // 10

# Name constants.
HAZARD_TRIGGER = "Hazard"
OBSTACLE_TRIGGER = "Obstacle"
PLAYER_SPAWN = "Spawn"

# Flag constants.
DEBUG_MODE = False

# Dimension constants.
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
INTERNAL_SCREEN_WIDTH, INTERNAL_SCREEN_HEIGHT = (
    1280,
    720,
)
TILE_SIZE = 24
PLAYER_SPRITE_WIDTH = 40
PLAYER_SPRITE_HEIGHT = 40
PLAYER_SHADOW_WIDTH_SCALE = 2
PLAYER_SHADOW_HEIGHT_SCALE = 3
ENEMY_SPRITE_WIDTH = 16
ENEMY_SPRITE_HEIGHT = 16
ENEMY_SHADOW_WIDTH_SCALE = 1.5
ENEMY_SHADOW_HEIGHT_SCALE = 3.5

# Gameplay constants.
PLAYER_VEL = 2
ENEMY_VEL = 1
MAX_PLAYER_HEALTH = 8
MAX_ENEMY_HEALTH = 4
PLAYER_KNOCKBACK_DISTANCE = PLAYER_SPRITE_WIDTH // 2
PLAYER_SWORD_DAMAGE = 1
ENEMY_ALERT_RADIUS = 200
ENEMY_CONTACT_DAMANGE = 1
ENEMY_KNOCKBACK_DISTANCE = ENEMY_SPRITE_WIDTH * 2
ENEMY_FLASH_FRAMES = FPS
PLAYER_INVISIBILITY_FRAMES = FPS * 2

# Color constants.
SHADOW_COLOR = (0, 0, 0, 50)
BACKGROUND_COLOR = "#3d8baf"
HAZARD_TRIGGER_DEBUG_COLOR = "Red"
OBSTACLE_TRIGGER_DEBUG_COLOR = "Yellow"
RADIUS_DEBUG_COLOR = "Green"
RADIUS_LINE_DEBUG_COLOR = "Blue"
ALPHA_MAX = 255
ALPHA_TRANSPARENT = 32
