SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
INTERNAL_SCREEN_WIDTH, INTERNAL_SCREEN_HEIGHT = (
    1280,
    720,
)  # For performance reason we set this to 1:1 with the main screen's size.
TILE_SIZE = 24
PLAYER_VEL = 2
PLAYER_WIDTH = 40
PLAYER_HEIGHT = 40
ANIMATION_DELAY = 8
FPS = 60
CAPTION = "Dungeon Breakout"
BACKGROUND_COLOR = "#3d8baf"
SCALE_SPEED = 0.1
DEFAULT_SCALE = 2
MIN_SCALE = 1
MAX_SCALE = 2
HAZARD_TRIGGER = "hazard"
OBSTACLE_TRIGGER = "obstacle"
HAZARD_TRIGGER_DEBUG_COLOR = "Red"
OBSTACLE_TRIGGER_DEBUG_COLOR = "Yellow"
TRIGGER_DEBUG = False
