# Essential constants.
FPS = 60
CAPTION = "Dungeon Breakout"
BACKGROUND_COLOR = "#3d8baf"
DEFAULT_SCALE = 2
MIN_SCALE = 1
MAX_SCALE = 2
NORMAL_ANIMATION_SPEED = 0.15
SWINGING_ANIMATION_SPEED = 0.25
SCALE_SPEED = 0.1
HAZARD_TRIGGER = "hazard"
OBSTACLE_TRIGGER = "obstacle"
HAZARD_TRIGGER_DEBUG_COLOR = "Red"
OBSTACLE_TRIGGER_DEBUG_COLOR = "Yellow"
TRIGGER_DEBUG = False

# Dimension constants.
SCREEN_WIDTH, SCREEN_HEIGHT = 1280, 720
INTERNAL_SCREEN_WIDTH, INTERNAL_SCREEN_HEIGHT = (
    1280,
    720,
)  # For performance reason we set this to 1:1 with the main screen's size.
TILE_SIZE = 24
PLAYER_SPRITE_WIDTH = 40
PLAYER_SPRITE_HEIGHT = 40

# Logic constants.
PLAYER_VEL = 2
